### ISSUE TITLE
Allow to set Ice temperature in place of Glen A.

### ISSUE THREAD

**Issue by fmaussion** [OGGM/oggm-edu-notebooks#72]
Heard in a feedback call today.

There is a table of Ice Temps <-> Glen A relationship in Physics of Glaciers that can be used to set ice temp (which is a more sensible variable) instead of A.

**Comment by Holmgren825** [comment]
This needs some thinking/discussion I think. Table provides discrete values, which would work. But ideally I think it would be nice to use for example eq. 3.35 (p.72) for continuous values of A for user provided T. However selecting $A_*$ is not trivial from what I understand.

![image](https://user-images.githubusercontent.com/56769803/172582476-9351a406-ae9e-4e6d-90d0-706eea204f55.png)

For reference table is on p.75.

**Comment by fmaussion** [comment]
cc @ehultee ,  @skachuck and @jbassis who suggested that.

**Comment by fmaussion** [comment]
I think the easiest would be to fit a function to this table and allow user to set any temp between the bounds

**Comment by ehultee** [comment]
In SERMeQ I have a temperature variable and I think it is just a lookup table...the user can only choose certain pre-determined values.  _A_ varies nonlinearly over several orders of magnitude, and it's especially weird near common temperate ice values.  A continuous function would be easy to use but could produce surprising results.

I'd have to look again at the text, but I'd also guess that we don't have a lot of lab measurements to resolve the shape of the important nonlinearities.

So the question is: how much of that do we want the student user to encounter?  It could be quite instructive for students to see sensitivity to (poorly known) temperature, but they would probably need sufficient explanation from an instructor.

**Comment by jbassis** [comment]
Does the Cuffy and Paterson functional form for the temperature dependence
of the rate parameter not work for alpine glaciers?  There is a
discontinuity in the activation energy at -10 C, but it gives reasonable
results for the Greenland and Antarctic ice sheets where you know the
temperature.  That is what we use for the ice sheet models, although some
models use the simpler parameterization developed by Roger Hooke.

-Jeremy




Jeremy Bassis (he/him/his)
Associate Professor/Graduate Program Chair
Department of Climate and Space Sciences and Engineering

**Comment by ehultee** [comment]
@Holmgren825 can you find the calibrated value of _A*_ and use that?  

We could if necessary add a little text cell the first time this adjustment is possible in a notebook, explaining key issues as Jeremy outlines above.

IMO it's better to use something that's already in wide use (e.g. C&P's existing functional form), rather than doing an ersatz fit to the table and coming up with _slightly_ different results from what students might find elsewhere.  Nuance is great but can be confusing for students who are encountering ice dynamics for the first time.

**Comment by ehultee** [comment]
By "in wide use" I mean the functional form of _A_ that C&P already give.  The equation Erik referenced first.  Maybe it's the same as a log-linear fit to the table anyway!  Since I'm a van der Veen type, I wouldn't know offhand 😅

**Comment by fmaussion** [comment]
OK here is the implementation:

```python
t = [0, -2, -5, -10, -15, -20, -25, -30, -35, -40, -45, -50]
a = [2.4*1e-24, 1.7*1e-24, 9.3*1e-25, 3.5*1e-25, 2.1*1e-25, 1.2*1e-25, 6.8*1e-26, 3.7*1e-26, 2.0*1e-26, 1.0*1e-26, 5.2*1e-27, 2.6*1e-27]

a_star = 3.5 * 1e-25
q_plus = 115_000
t_star = 263 + 7*1e-8
q_minus = 60_000
r = 8.314

def cp_glena(t):

    t = t + 273
    t_h = t + 7*1e-8

    if t < t_star:
        q_c = q_minus
    else:
        q_c = q_plus

    return a_star * np.exp(- (q_c / r) * (1 / t_h - 1 / t_star))

a_book = [cp_glena(tmp) for tmp in t]

plt.plot(t, a, 'o-', label='Table');
plt.plot(t, a_book, 'o-', label='Analytic');
plt.semilogy();
plt.ylabel('A'); plt.xlabel('T'); plt.legend();
```

![image](https://user-images.githubusercontent.com/10050469/172660874-a3283a47-bddd-4912-9b10-0dc83e77cb98.png)

**Comment by fmaussion** [comment]
(reference A* is given on page 74)

**Comment by Holmgren825** [comment]
Awesome! To me using the equation makes total sense. If the students can only select from a table of approved temperatures, they might as well enter the value of A directly. I will implement eq 3.35 as Fabi did above.

**Comment by jbassis** [comment]
What kind of supervisor doesn't constantly have C&P loaned out to students
with an extra copy at home under their pillow?  I have Van der Veen, Hooke
and C&P all loaned out.  Van der Veen (first edition) quotes Hooke's
functional form (equations 2.4.1-2.4.2). I think either of those are decent
starts, but would favor C&P because it is the most recent and a lot of
synthesis goes into the new calibration.

Bonus question: Is it possible to allow advanced students to add their own
preferred rheology?  For example, I do flubber experiments and they try to
calibrate a flow law using observations of the deformation of the goo.  It
would be fun if they would then model their goo glacier.  Or play around
with a Newtonian rheology.







Jeremy Bassis (he/him/his)
Associate Professor/Graduate Program Chair
Department of Climate and Space Sciences and Engineering
