### ISSUE TITLE
Slope experiments now very difficult

### ISSUE THREAD

**Issue by ehultee** [OGGM/oggm-edu-notebooks#82]
I am trying to update my [notebook 1](https://github.com/ehultee/glaciology-labs/blob/main/1_glacier_bed_slope.ipynb) to work with the new Edu tools.  The reason I include glacier bed slope as the first experiment is to build on a hands-on lab activity with glacier goo, in which the students modify the slope of an underlying "valley" by inclining the tube where their goo flows.

Several choices in the new Edu package make this very difficult to translate.  For example:

- `slopes` is not accessible as an attribute; it is provided at initialization but then (apparently?) not recoverable
- The new `GlacierCollection` plotting utility gives an error if the glaciers do not all have the same bed slope
- The glacier surface elevation is not stored in `Glacier.history`, so I cannot even make a workaround with my helper plotting function I previously used

If we want to make an Edu lab that builds on goo experiments, we need this functionality.

**Comment by Holmgren825** [comment]
Hey @ehultee ,
It is correct that the `slopes` argument passed to `GlacierBed` is not assigned to any single attribute. It is however used in the setup of the `GlacerBed`. So one can still create beds with a specific slope, or many slopes if one want to do that. The intro notebook shows some of examples of this. But it is probably a **very** good idea to expose the slopes as an attribute (maybe read only), at least for annotation purposes. This shouldn't be hard. I'm not sure about changing slopes after initilization.

Surface elevation is available in either `Glacer.current_state` which is the current `RectangularBedFlowline` or in the `Glacier.state_history` which holds the whole geometric history of the glacier (This is a standard flowline diagnostics ds from oggm). For the latter, the bed height and thickness have to be combined for the surface height.

The plotting utility requires a little bit more thinking. Currently it fails since it tries to plot all glaciers on single bed. Why it doesn't allow plotting of multiple beds is purely out of aesthetic reasons.  `GlacierCollection.plot_history()` works with different slopes, but this does not show surface height.

**Comment by fmaussion** [comment]
@ehultee did you manage to translate your notebook in the new framework? I can try to address some of the points, or at least give a more meaningful error message

**Comment by ehultee** [comment]
The version I updated to teach last semester is here: https://github.com/ehultee/glaciology-labs/blob/main/1_glacier_bed_slope-2022.ipynb 

I have no memory of what I translated, removed, dropped etc.  Let me know if anything doesn't make sense (very probable)

**Comment by fmaussion** [comment]
Now it should be less difficult! 

https://oggm.org/oggm-edu-notebooks/oggm-edu/ice_on_incline.html

![](https://oggm.org/oggm-edu-notebooks/_images/ice_on_incline_72_0.png)
